# Initialisation
INITED=0;
THEME_NAME="Dudebarf";
VERSION = "1.0";

# Operating mode
MODE = Plymouth.GetMode();
IS_SHUTDOWN = (MODE == "shutdown" || MODE == "suspend");

# Progress and timing
PROGRESS=0;
DURATION=0;
TICK=0;

# Password / Normal status
STATUS = "normal";

HZ=50;
PI = 3.14;
HALFPI = PI / 2.0;
TWOPI = 2 * PI;
ARC = TWOPI / HZ;

# Fonts, Colors etc
FONT2 = "Noto Sans 12";
FONT1 = "Noto Sans 14";

SPRITES_DEFAULT_Z = 1000;
